import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/global.scss";
import { Header } from "@/components/shared/Header/Header";

const roboto = Roboto({
  weight: ["400", "500", "600", "700", "800", "900"], // какие начертания нужны
  subsets: ["cyrillic"],
  variable: "--font-roboto", // своя переменная
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={roboto.variable}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
